/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : Script
 #	author : miyako
 #	2018/06/20
 #
 # --------------------------------------------------------------------------------*/


#include "4DPluginAPI.h"
#include "4DPlugin.h"

void PluginMain(PA_long32 selector, PA_PluginParameters params)
{
	try
	{
		PA_long32 pProcNum = selector;
		sLONG_PTR *pResult = (sLONG_PTR *)params->fResult;
		PackagePtr pParams = (PackagePtr)params->fParameters;

		CommandDispatcher(pProcNum, pResult, pParams); 
	}
	catch(...)
	{

	}
}

void CommandDispatcher (PA_long32 pProcNum, sLONG_PTR *pResult, PackagePtr pParams)
{
	switch(pProcNum)
	{
// --- Script

		case 1 :
			Script_parse(pResult, pParams);
			break;

	}
}

#pragma mark MyActiveScriptSite

#if VERSIONWIN

class MyActiveScriptSite :
public IActiveScriptSite,
public IActiveScriptSiteWindow {
	private:
	ULONG m_cRefCount; // Reference count
	HWND m_hWnd;
	public:

	MyActiveScriptSite() : m_cRefCount(1), m_hWnd(NULL) {}
	~MyActiveScriptSite() {}
	
	// IUnknown methods...
	virtual HRESULT _stdcall QueryInterface(REFIID riid, void **ppvObject) {
		if (ppvObject == NULL) return E_POINTER;

		if (IsEqualIID(riid, IID_IUnknown) || IsEqualIID(riid, IID_IActiveScriptSite))
		{
			*ppvObject = static_cast<IActiveScriptSite *>(this);
		}
		else if (IsEqualIID(riid, IID_IActiveScriptSiteWindow))
		{
			*ppvObject = static_cast<IActiveScriptSiteWindow *>(this);
		}
		else
		{
			*ppvObject = NULL;
			return E_NOINTERFACE;
		}

		AddRef();
		return S_OK;
	}
	
	virtual ULONG _stdcall AddRef(void) {
		return InterlockedIncrement(&m_cRefCount);
	}
	
	virtual ULONG _stdcall Release(void) {
		// NOTE: g_ActiveScriptSite (below) is a global/static object, not a
		// heap-allocated one, so this must never call "delete this" -- doing so
		// on a non-heap object is undefined behavior. Floor the refcount at 0
		// and let the object simply live for the lifetime of the plugin.
		LONG count = InterlockedDecrement(&m_cRefCount);
		if (count < 0)
		{
			InterlockedIncrement(&m_cRefCount); // undo: never go negative
			return 0;
		}
		return (ULONG)count;
	}
	
	// IActiveScriptSite methods...
	virtual HRESULT _stdcall GetLCID(LCID *plcid) {
		if (plcid == NULL) return E_POINTER;
		*plcid = GetUserDefaultLCID();
		return S_OK;
	}
	
	virtual HRESULT _stdcall GetItemInfo(LPCOLESTR pstrName,
																			 DWORD dwReturnMask,
																			 IUnknown **ppunkItem,
																			 ITypeInfo **ppti) {
		return TYPE_E_ELEMENTNOTFOUND;
	}
	
	virtual HRESULT __stdcall GetDocVersionString(BSTR *pbstrVersion) {
		*pbstrVersion = SysAllocString(L"1.0");
		return S_OK;
	}
	
	virtual HRESULT __stdcall OnScriptTerminate(const VARIANT *pvarResult,
																							const EXCEPINFO *pexcepInfo) {
		return S_OK;
	}
	
	virtual HRESULT __stdcall OnStateChange(SCRIPTSTATE ssScriptState) {
		return S_OK;
	}
	
	virtual HRESULT __stdcall OnScriptError(IActiveScriptError *pscriptError) {
		return S_OK;
	}
	
	virtual HRESULT __stdcall OnEnterScript(void) {
		return S_OK;
	}
	
	virtual HRESULT __stdcall OnLeaveScript(void) {
		return S_OK;
	}
	
	// IActiveScriptSiteWindow methods...
	virtual HRESULT __stdcall GetWindow(HWND *phWnd) {
		*phWnd = m_hWnd;
		return S_OK;
	}
	
	virtual HRESULT __stdcall EnableModeless(BOOL fEnable) {
		return S_OK;
	}
};

#pragma mark OleInitClass

class OleInitClass {
	
	public:
	OleInitClass() {
		OleInitialize(NULL);
	}
	
	~OleInitClass() {
		OleUninitialize();
	}
};

MyActiveScriptSite g_ActiveScriptSite;
OleInitClass g_OleInitClass;

// ------------------------------------ Script ------------------------------------

/* https://www.codeproject.com/Articles/14905/COM-in-plain-C-Part */

HRESULT getEngineGuid(LPCWSTR extension, GUID *guidBuffer)
{
	wchar_t   buffer[100];
	HKEY      hk = NULL;
	DWORD     size;
	HKEY      subKey;
	DWORD     type;
	
	// See if this file extension is associated
	// with an ActiveX script engine
	if (!RegOpenKeyExW(HKEY_CLASSES_ROOT, extension, 0,
										KEY_QUERY_VALUE|KEY_READ, &hk))
	{
		type = REG_SZ;
		size = sizeof(buffer);
		size = RegQueryValueExW(hk, 0, 0, &type,
													 (LPBYTE)&buffer[0], &size);
		RegCloseKey(hk);
		hk = NULL;
		if (!size)
		{
			// The engine set an association.
			// We got the Language string in buffer[]. Now
			// we can use it to look up the engine's GUID
			
			// Open HKEY_CLASSES_ROOT\{LanguageName}
		again:   size = sizeof(buffer);
			if (!RegOpenKeyExW(HKEY_CLASSES_ROOT, (LPCWSTR)&buffer[0], 0,
												KEY_QUERY_VALUE|KEY_READ, &hk))
			{
				// Read the GUID (in string format)
				// into buffer[] by querying the value of CLSID
				if (!RegOpenKeyExW(hk, L"CLSID", 0,
													KEY_QUERY_VALUE|KEY_READ, &subKey))
				{
					size = RegQueryValueExW(subKey, 0, 0, &type,
																	(LPBYTE)&buffer[0], &size);
					RegCloseKey(subKey);
				}
				else if (extension)
				{
					// If an error, see if we have a "ScriptEngine"
					// key under here that contains
					// the real language name
					if (!RegOpenKeyExW(hk, L"ScriptEngine", 0,
														KEY_QUERY_VALUE|KEY_READ, &subKey))
					{
						size = RegQueryValueExW(subKey, 0, 0, &type,
																	 (LPBYTE)&buffer[0], &size);
						RegCloseKey(subKey);
						if (!size)
						{
							RegCloseKey(hk);
							hk = NULL;
							extension = 0;
							goto again;
						}
					}
				}
			}
			else
			{
				hk = NULL; // RegOpenKeyExW failed: nothing was opened, don't close it below
			}
			
			if (hk != NULL)
			{
				RegCloseKey(hk);
				hk = NULL;
			}
			
			if (!size)
			{
				// Convert the GUID string to a GUID
				// and put it in caller's guidBuffer
				CLSIDFromString(&buffer[0], guidBuffer);
				return(size);
			}
		}
	}
	
	return(E_FAIL);
}

#endif

void Script_parse(sLONG_PTR *pResult, PackagePtr pParams)
{
#if VERSIONWIN
	C_TEXT Param1_engine;
	C_TEXT Param2_script;
	C_TEXT returnValue;

	Param1_engine.fromParamAtIndex(pParams, 1);
	Param2_script.fromParamAtIndex(pParams, 2);

	wchar_t *engine = (wchar_t *)Param1_engine.getUTF16StringPtr();
	wchar_t *script = (wchar_t *)Param2_script.getUTF16StringPtr();
	
	HRESULT hr = S_OK;
	
	EXCEPINFO ei;
	ZeroMemory(&ei, sizeof(ei));
	
	VARIANT result;
	VariantInit(&result);
	
	IActiveScript *pActiveScript = NULL;
	IActiveScriptParse *pActiveScriptParse = NULL;

	// COM is initialized per-thread. 4D can invoke plugin commands from worker/
	// preemptive process threads other than the one that ran this DLL's static
	// initializers, so a single global OleInitialize() at load time is not
	// sufficient -- ensure THIS thread is COM-initialized before using it here.
	HRESULT hrCoInit = CoInitializeEx(NULL, COINIT_APARTMENTTHREADED);
	bool comInitializedHere = (hrCoInit == S_OK); // S_FALSE/RPC_E_CHANGED_MODE => already initialized elsewhere; don't uninit what we didn't init

	CLSID CLSID_Script;
	hr = CLSIDFromProgID(engine, &CLSID_Script);
	
	if (FAILED(hr))
	{
		hr = CLSIDFromString(engine, &CLSID_Script);
	}

	if (FAILED(hr))
	{
		hr = getEngineGuid(engine, &CLSID_Script);
	}

	if (SUCCEEDED(hr))
	{
		hr = CoCreateInstance(CLSID_Script,
													NULL,
													CLSCTX_ALL,
													IID_IActiveScript,
													(void **)&pActiveScript);	
		if (SUCCEEDED(hr))
		{
			hr = pActiveScript->SetScriptSite(&g_ActiveScriptSite);
			
			if (SUCCEEDED(hr))
			{
				hr = pActiveScript->QueryInterface(IID_IActiveScriptParse,
					(void **)&pActiveScriptParse);

				if (SUCCEEDED(hr))
				{
					hr = pActiveScriptParse->InitNew();
					
					if (SUCCEEDED(hr))
					{
						hr = pActiveScriptParse->ParseScriptText(script,
							0,
							0,
							0,
							0,
							0,
							SCRIPTTEXT_ISEXPRESSION | SCRIPTTEXT_ISVISIBLE,
							&result,
							&ei);
						if (SUCCEEDED(hr))
						{
							SYSTEMTIME systime;
							CUTF16String u16;
							CUTF8String u8;
							std::vector<char>buf(100);

							switch (result.vt)
							{
							case VT_EMPTY:
							case VT_NULL:
								break;

							case VT_R4:
								sprintf_s((char *)&buf[0], 100, "%f", result.fltVal);
								u8 = (const uint8_t *)&buf[0];
								returnValue.setUTF8String(&u8);
								break;
							case VT_R8:
							{
								// "%16.16lf" has no upper bound on output length (16 is only a
								// minimum field width) -- a large-magnitude double (e.g. 1e300)
								// needs 300+ characters and previously overflowed the fixed
								// 100-byte buffer, which made sprintf_s invoke the CRT's
								// invalid-parameter handler and abort() the whole host process.
								// Compute the required length first and size the buffer to fit.
								int needed = _scprintf("%16.16lf", result.dblVal);
								if (needed < 0) needed = 0;
								std::vector<char> dblBuf((size_t)needed + 1);
								sprintf_s(&dblBuf[0], dblBuf.size(), "%16.16lf", result.dblVal);
								u8 = (const uint8_t *)&dblBuf[0];
								returnValue.setUTF8String(&u8);
								break;
							}

							case VT_I2:
								sprintf_s((char *)&buf[0], 100, "%d", result.intVal);
								u8 = (const uint8_t *)&buf[0];
								returnValue.setUTF8String(&u8);
								break;
							case VT_UI2:
								sprintf_s((char *)&buf[0], 100, "%u", result.uintVal);
								u8 = (const uint8_t *)&buf[0];
								returnValue.setUTF8String(&u8);
								break;

							case VT_INT:
							case VT_I4:
								sprintf_s((char *)&buf[0], 100, "%I32d", result.lVal);
								u8 = (const uint8_t *)&buf[0];
								returnValue.setUTF8String(&u8);
								break;
							case VT_UINT:
							case VT_UI4:
								sprintf_s((char *)&buf[0], 100, "%I32u", result.ulVal);
								u8 = (const uint8_t *)&buf[0];
								returnValue.setUTF8String(&u8);
								break;

							case VT_I8:
								sprintf_s((char *)&buf[0], 100, "%I64d", result.llVal);
								u8 = (const uint8_t *)&buf[0];
								returnValue.setUTF8String(&u8);
								break;
							case VT_UI8:
								sprintf_s((char *)&buf[0], 100, "%I64u", result.ullVal);
								u8 = (const uint8_t *)&buf[0];
								returnValue.setUTF8String(&u8);
								break;

							case VT_BSTR:
								u16 = (const PA_Unichar *)result.bstrVal;
								returnValue.setUTF16String(&u16);
								break;

							case VT_DATE:
								VariantTimeToSystemTime(result.date, &systime);
								sprintf_s((char *)&buf[0], 100, "%04u-%02u-%02uT%02d:%02d:%02d.%03d", 
									systime.wYear, 
									systime.wMonth, 
									systime.wDay,  
									systime.wHour, 
									systime.wMinute, 
									systime.wSecond,
									systime.wMilliseconds);
								u8 = (const uint8_t *)&buf[0];
								returnValue.setUTF8String(&u8);
								break;
							}

							// result may own a BSTR (VT_BSTR) or an interface (VT_DISPATCH /
							// VT_UNKNOWN, e.g. a JScript Date() object) that was never released
							// before. VariantClear releases whatever resource it holds; any
							// data needed above was already copied out via u8/u16 before this.
							VariantClear(&result);

							pActiveScript->SetScriptState(SCRIPTSTATE_CONNECTED);
						}/* ParseScriptText */
						
					}/* InitNew */
					
					pActiveScriptParse->Release();
					pActiveScriptParse = NULL;
				}/* QueryInterface */
			}
			pActiveScript->Close();
			pActiveScript->Release();
			pActiveScript = NULL;
		}/* CoCreateInstance */

	}

	if (comInitializedHere)
	{
		CoUninitialize();
	}
	
	returnValue.setReturn(pResult);
#endif
}
