/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Script
 #	author : miyako
 #	2018/06/20
 #
 # --------------------------------------------------------------------------------*/

#if VERSIONWIN
#include <initguid.h>
#include <ole2.h>
#include <activscp.h>
#include <atlstr.h>
#endif

// --- Script
void Script_parse(sLONG_PTR *pResult, PackagePtr pParams);
